name: wafer-seg-class
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pytorch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=12.1
  - numpy=1.26.2
  - pandas=2.1.3
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - pyyaml=6.0.1
  - tqdm=4.66.1
  - opencv=4.8.1
  - pip
  - pip:
    - hypothesis>=6.82
    - python-pptx>=0.6.21
    - tensorboard>=2.14
